### Summary

We have several reports from users with LDAP sync enabled who are experiencing random users being blocked, only to be unblocked again in the future.

Browsing `lib/gitlab/ldap/access.rb`, particularly this method: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ldap/access.rb#L34 it appears that if the ldap_user is not found for any reason, the user is blocked. This could explain the symptoms seen if, e.g., transient network errors return nil out of `Gitlab::LDAP::Person.find_by_dn(user.ldap_identity.extern_uid, adapter)` rather than an exception.

The `adapter` is an instance of `Gitlab::LDAP::Adapter`, which catches a range of errors in `ldap_search`, returning an empty array. Timeouts will block users, for instance.

### Steps to reproduce

Stub `ldap_search` to return any LDAP or timeout error, then run the LdapSyncWorker with some LDAP users in the DB.


### Expected behavior

Users should not be blocked 

### Actual behavior

Users will be blocked